// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace housing.ConsoleApp
{
    public partial class Housing
    {
        /// <summary>
        /// model input class for Housing.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"SquareFeet")]
            public float SquareFeet { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Bedrooms")]
            public float Bedrooms { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Bathrooms")]
            public float Bathrooms { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Neighborhood")]
            public string Neighborhood { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"YearBuilt")]
            public float YearBuilt { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Price")]
            public float Price { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Housing.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"SquareFeet")]
            public float SquareFeet { get; set; }

            [ColumnName(@"Bedrooms")]
            public float Bedrooms { get; set; }

            [ColumnName(@"Bathrooms")]
            public float Bathrooms { get; set; }

            [ColumnName(@"Neighborhood")]
            public float[] Neighborhood { get; set; }

            [ColumnName(@"YearBuilt")]
            public float YearBuilt { get; set; }

            [ColumnName(@"Price")]
            public float Price { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("housing.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
